#include "json_parser.h"

#include <assert.h>
#include <stdint.h>
#include <string.h>

int main(void) {
    const uint8_t *dom_doc = (uint8_t*)"{\"na\\u006de\":\"line\\nbreak\",\"quote\":\"\\\"\",\"nums\":[123,-2],\"ok\":true,\"none\":null,\"big\":18446744073709551615}";
    const uint8_t *float_doc = (uint8_t*)"{\"frac\":1.5,\"exp\":1e3,\"huge\":18446744073709551616,\"items\":[-2.25,1000.0]}";

    assert(json_parser_parity_suite() == 1);

    assert(json_parser_checksum((uint8_t*)"{}") == 47);
    assert(json_parser_checksum((uint8_t*)"[]") == 43);
    assert(json_parser_checksum((uint8_t*)"{\"a\":1}") == 89);
    assert(json_parser_checksum((uint8_t*)"[true,false,null]") == 152);
    assert(json_parser_checksum((uint8_t*)"{\"items\":[1,2,3],\"ok\":true}") == 234);
    assert(json_parser_checksum((uint8_t*)"{\"a\":[1,2}") < 0);

    assert(json_parser_ast_checksum((uint8_t*)"{}") == 47);
    assert(json_parser_ast_checksum((uint8_t*)"[]") == 43);
    assert(json_parser_ast_checksum((uint8_t*)"{\"a\":1}") == 89);
    assert(json_parser_ast_checksum((uint8_t*)"[true,false,null]") == 152);
    assert(json_parser_ast_checksum((uint8_t*)"{\"items\":[1,2,3],\"ok\":true}") == 234);
    assert(json_parser_ast_checksum((uint8_t*)"{\"a\":[1,2}") < 0);

    assert(json_parser_ast_node_count((uint8_t*)"{\"items\":[1,2,3],\"ok\":true}") > 0);
    assert(json_parser_ast_object_len((uint8_t*)"{\"a\":1,\"b\":2}") == 2);
    assert(json_parser_ast_object_len((uint8_t*)"[") < 0);

    assert(json_parser_ast_field_string_eq((uint8_t*)dom_doc, (uint8_t*)"name", (uint8_t*)"line\nbreak") == 1);
    assert(json_parser_ast_field_string_eq((uint8_t*)dom_doc, (uint8_t*)"quote", (uint8_t*)"\"") == 1);
    assert(json_parser_ast_field_string_eq((uint8_t*)dom_doc, (uint8_t*)"missing", (uint8_t*)"x") < 0);

    assert(json_parser_ast_field_bool((uint8_t*)dom_doc, (uint8_t*)"ok") == 1);
    assert(json_parser_ast_field_is_null((uint8_t*)dom_doc, (uint8_t*)"none") == 1);
    assert(json_parser_ast_field_kind((uint8_t*)dom_doc, (uint8_t*)"name") == 3);
    assert(json_parser_ast_field_kind((uint8_t*)dom_doc, (uint8_t*)"nums") == 4);
    assert(json_parser_ast_field_kind((uint8_t*)dom_doc, (uint8_t*)"missing") < 0);
    assert(json_parser_ast_field_number_kind((uint8_t*)"{\"small\":123,\"neg\":-2,\"frac\":1.5,\"huge\":18446744073709551616}", (uint8_t*)"small") == 0);
    assert(json_parser_ast_field_number_kind((uint8_t*)"{\"small\":123,\"neg\":-2,\"frac\":1.5,\"huge\":18446744073709551616}", (uint8_t*)"neg") == 1);
    assert(json_parser_ast_field_number_kind((uint8_t*)"{\"small\":123,\"neg\":-2,\"frac\":1.5,\"huge\":18446744073709551616}", (uint8_t*)"frac") == 2);
    assert(json_parser_ast_field_number_kind((uint8_t*)"{\"small\":123,\"neg\":-2,\"frac\":1.5,\"huge\":18446744073709551616}", (uint8_t*)"huge") == 3);
    assert(json_parser_ast_field_number_kind((uint8_t*)"{\"small\":123,\"neg\":-2,\"frac\":1.5,\"huge\":18446744073709551616}", (uint8_t*)"missing") < 0);
    assert(json_parser_ast_field_string_len((uint8_t*)dom_doc, (uint8_t*)"name") == 10);
    assert(json_parser_ast_field_string_len((uint8_t*)dom_doc, (uint8_t*)"quote") == 1);
    assert(json_parser_ast_field_string_len((uint8_t*)dom_doc, (uint8_t*)"nums") < 0);
    uint8_t field_name_buf[32] = {0};
    uint8_t field_quote_buf[8] = {0};
    uint8_t field_small_buf[4] = {0};
    assert(json_parser_ast_field_string_copy((uint8_t*)dom_doc, (uint8_t*)"name", field_name_buf, sizeof(field_name_buf)) == 10);
    assert(strcmp((char*)field_name_buf, "line\nbreak") == 0);
    assert(json_parser_ast_field_string_copy((uint8_t*)dom_doc, (uint8_t*)"quote", field_quote_buf, sizeof(field_quote_buf)) == 1);
    assert(strcmp((char*)field_quote_buf, "\"") == 0);
    assert(json_parser_ast_field_string_copy((uint8_t*)dom_doc, (uint8_t*)"name", field_small_buf, sizeof(field_small_buf)) == 10);
    assert(json_parser_ast_field_string_copy((uint8_t*)dom_doc, (uint8_t*)"nums", field_name_buf, sizeof(field_name_buf)) < 0);
    assert(json_parser_ast_array_field_len((uint8_t*)dom_doc, (uint8_t*)"nums") == 2);
    assert(json_parser_ast_object_field_len((uint8_t*)"{\"meta\":{\"ok\":true,\"none\":null},\"nums\":[1,2]}", (uint8_t*)"meta") == 2);
    assert(json_parser_ast_object_field_len((uint8_t*)"{\"meta\":{\"ok\":true,\"none\":null},\"nums\":[1,2]}", (uint8_t*)"nums") < 0);

    int64_t first_num = 0;
    int64_t second_num = 0;
    int64_t object_second = 0;
    int64_t array_root_second = 0;
    int64_t object_array_kind = -1;
    int64_t object_object_kind = -1;
    int64_t array_string_kind = -1;
    int64_t array_array_kind = -1;
    int64_t array_object_kind = -1;
    int64_t object_bool = -1;
    int64_t object_null = -1;
    int64_t array_bool = -1;
    int64_t array_null = -1;
    int64_t missing_num = 99;
    uint64_t big_num = 0;
    double field_f64 = 0.0;
    float field_f32 = 0.0f;
    assert(json_parser_ast_array_field_i64_at((uint8_t*)dom_doc, (uint8_t*)"nums", 0u, &first_num) == 1);
    assert(json_parser_ast_array_field_i64_at((uint8_t*)dom_doc, (uint8_t*)"nums", 1u, &second_num) == 1);
    assert(json_parser_ast_array_field_i64_at((uint8_t*)dom_doc, (uint8_t*)"nums", 2u, &missing_num) == 0);
    assert(json_parser_ast_field_f64((uint8_t*)float_doc, (uint8_t*)"frac", &field_f64) == 1);
    assert(field_f64 == 1.5);
    assert(json_parser_ast_field_f32((uint8_t*)float_doc, (uint8_t*)"frac", &field_f32) == 1);
    assert(field_f32 == 1.5f);
    assert(json_parser_ast_field_f64((uint8_t*)float_doc, (uint8_t*)"huge", &field_f64) == 1);
    assert(field_f64 == 18446744073709551616.0);
    assert(json_parser_ast_field_f32((uint8_t*)float_doc, (uint8_t*)"huge", &field_f32) == 1);
    assert(field_f32 > 1.0e19f);
    assert(json_parser_ast_array_field_f64_at((uint8_t*)float_doc, (uint8_t*)"items", 0u, &field_f64) == 1);
    assert(field_f64 == -2.25);
    assert(json_parser_ast_array_field_f32_at((uint8_t*)float_doc, (uint8_t*)"items", 1u, &field_f32) == 1);
    assert(field_f32 == 1000.0f);
    assert(json_parser_ast_array_field_kind_at((uint8_t*)"{\"items\":[\"Ada\",true,null,[1,2],{\"ok\":true}]}", (uint8_t*)"items", 0u) == 3);
    assert(json_parser_ast_array_field_number_kind_at((uint8_t*)"{\"nums\":[123,-2,1.5,18446744073709551616]}", (uint8_t*)"nums", 0u) == 0);
    assert(json_parser_ast_array_field_number_kind_at((uint8_t*)"{\"nums\":[123,-2,1.5,18446744073709551616]}", (uint8_t*)"nums", 1u) == 1);
    assert(json_parser_ast_array_field_number_kind_at((uint8_t*)"{\"nums\":[123,-2,1.5,18446744073709551616]}", (uint8_t*)"nums", 2u) == 2);
    assert(json_parser_ast_array_field_number_kind_at((uint8_t*)"{\"nums\":[123,-2,1.5,18446744073709551616]}", (uint8_t*)"nums", 3u) == 3);
    assert(json_parser_ast_array_field_number_kind_at((uint8_t*)"{\"nums\":[123,-2,1.5,18446744073709551616]}", (uint8_t*)"nums", 4u) < 0);
    assert(json_parser_ast_array_field_string_len_at((uint8_t*)"{\"items\":[\"Ada\",\"\u263A\"]}", (uint8_t*)"items", 0u) == 3);
    assert(json_parser_ast_array_field_string_len_at((uint8_t*)"{\"items\":[\"Ada\",\"\u263A\"]}", (uint8_t*)"items", 1u) == 3);
    assert(json_parser_ast_array_field_string_len_at((uint8_t*)"{\"items\":[\"Ada\",\"\u263A\"]}", (uint8_t*)"items", 2u) < 0);
    uint8_t array_field_buf[16] = {0};
    uint8_t array_field_small_buf[3] = {0};
    assert(json_parser_ast_array_field_string_copy_at((uint8_t*)"{\"items\":[\"Ada\",\"\u263A\"]}", (uint8_t*)"items", 0u, array_field_buf, sizeof(array_field_buf)) == 3);
    assert(strcmp((char*)array_field_buf, "Ada") == 0);
    assert(json_parser_ast_array_field_string_copy_at((uint8_t*)"{\"items\":[\"Ada\",\"\u263A\"]}", (uint8_t*)"items", 1u, array_field_buf, sizeof(array_field_buf)) == 3);
    assert(strcmp((char*)array_field_buf, "\xE2\x98\xBA") == 0);
    assert(json_parser_ast_array_field_string_copy_at((uint8_t*)"{\"items\":[\"Ada\",\"\u263A\"]}", (uint8_t*)"items", 1u, array_field_small_buf, sizeof(array_field_small_buf)) == 3);
    assert(json_parser_ast_array_field_string_copy_at((uint8_t*)"{\"items\":[\"Ada\",\"\u263A\"]}", (uint8_t*)"items", 2u, array_field_buf, sizeof(array_field_buf)) < 0);
    assert(json_parser_ast_array_field_string_eq_at((uint8_t*)"{\"items\":[\"Ada\",true,null,[1,2],{\"ok\":true}]}", (uint8_t*)"items", 0u, (uint8_t*)"Ada") == 1);
    assert(json_parser_ast_array_field_bool_at((uint8_t*)"{\"items\":[\"Ada\",true,null,[1,2],{\"ok\":true}]}", (uint8_t*)"items", 1u) == 1);
    assert(json_parser_ast_array_field_is_null_at((uint8_t*)"{\"items\":[\"Ada\",true,null,[1,2],{\"ok\":true}]}", (uint8_t*)"items", 2u) == 1);
    assert(json_parser_ast_array_field_array_len_at((uint8_t*)"{\"items\":[\"Ada\",true,null,[1,2],{\"ok\":true}]}", (uint8_t*)"items", 3u) == 2);
    assert(json_parser_ast_array_field_object_len_at((uint8_t*)"{\"items\":[\"Ada\",true,null,[1,2],{\"ok\":true}]}", (uint8_t*)"items", 4u) == 1);
    assert(json_parser_ast_array_field_string_eq_at((uint8_t*)"{\"items\":[\"Ada\",true,null,[1,2],{\"ok\":true}]}", (uint8_t*)"items", 1u, (uint8_t*)"Ada") == 0);
    assert(json_parser_ast_array_field_bool_at((uint8_t*)"{\"items\":[\"Ada\",true,null,[1,2],{\"ok\":true}]}", (uint8_t*)"items", 0u) < 0);
    assert(json_parser_ast_array_field_kind_at((uint8_t*)"{\"items\":[\"Ada\",true,null,[1,2],{\"ok\":true}]}", (uint8_t*)"items", 5u) < 0);
    assert(json_parser_ast_array_field_object_len_at((uint8_t*)"{\"items\":[\"Ada\",true,null,[1,2],{\"ok\":true}]}", (uint8_t*)"items", 3u) < 0);
    assert(json_parser_ast_object_key_eq_at((uint8_t*)"{\"first\":1,\"second\":2,\"third\":3}", 0u, (uint8_t*)"first") == 1);
    assert(json_parser_ast_object_key_eq_at((uint8_t*)"{\"first\":1,\"second\":2,\"third\":3}", 1u, (uint8_t*)"second") == 1);
    assert(json_parser_ast_object_key_eq_at((uint8_t*)"{\"first\":1,\"second\":2,\"third\":3}", 3u, (uint8_t*)"missing") < 0);
    uint8_t object_key_buf[16] = {0};
    uint8_t object_key_small_buf[4] = {0};
    assert(json_parser_ast_object_key_len_at((uint8_t*)"{\"first\":1,\"second\":2,\"third\":3}", 0u) == 5);
    assert(json_parser_ast_object_key_len_at((uint8_t*)"{\"first\":1,\"second\":2,\"third\":3}", 1u) == 6);
    assert(json_parser_ast_object_key_len_at((uint8_t*)"{\"first\":1,\"second\":2,\"third\":3}", 3u) < 0);
    assert(json_parser_ast_object_key_copy_at((uint8_t*)"{\"first\":1,\"second\":2,\"third\":3}", 1u, object_key_buf, sizeof(object_key_buf)) == 6);
    assert(strcmp((char*)object_key_buf, "second") == 0);
    assert(json_parser_ast_object_key_copy_at((uint8_t*)"{\"first\":1,\"second\":2,\"third\":3}", 1u, object_key_small_buf, sizeof(object_key_small_buf)) == 6);
    assert(json_parser_ast_object_key_copy_at((uint8_t*)"{\"first\":1,\"second\":2,\"third\":3}", 3u, object_key_buf, sizeof(object_key_buf)) < 0);
    assert(json_parser_ast_object_field_i64_at((uint8_t*)"{\"first\":1,\"second\":2,\"third\":3}", 1u, &object_second) == 1);
    assert(json_parser_ast_object_field_f64_at((uint8_t*)float_doc, 2u, &field_f64) == 1);
    assert(field_f64 == 18446744073709551616.0);
    assert(json_parser_ast_object_field_f32_at((uint8_t*)float_doc, 1u, &field_f32) == 1);
    assert(field_f32 == 1000.0f);
    assert(json_parser_ast_object_value_string_eq_at((uint8_t*)"{\"name\":\"Ada\",\"ok\":true,\"none\":null}", 0u, (uint8_t*)"Ada") == 1);
    assert(json_parser_ast_object_field_bool_at((uint8_t*)"{\"name\":\"Ada\",\"ok\":true,\"none\":null}", 1u) == 1);
    assert(json_parser_ast_object_field_is_null_at((uint8_t*)"{\"name\":\"Ada\",\"ok\":true,\"none\":null}", 2u) == 1);
    assert(json_parser_ast_object_value_kind_at((uint8_t*)"{\"name\":\"Ada\",\"items\":[4,5],\"meta\":{\"ok\":true}}", 1u) == 4);
    assert(json_parser_ast_object_value_kind_at((uint8_t*)"{\"name\":\"Ada\",\"items\":[4,5],\"meta\":{\"ok\":true}}", 2u) == 5);
    assert(json_parser_ast_object_value_array_len_at((uint8_t*)"{\"name\":\"Ada\",\"items\":[4,5],\"meta\":{\"ok\":true}}", 1u) == 2);
    assert(json_parser_ast_object_value_object_len_at((uint8_t*)"{\"name\":\"Ada\",\"items\":[4,5],\"meta\":{\"ok\":true}}", 2u) == 1);
    assert(json_parser_ast_object_value_array_len_at((uint8_t*)"{\"name\":\"Ada\",\"items\":[4,5],\"meta\":{\"ok\":true}}", 0u) < 0);
    assert(json_parser_ast_object_value_number_kind_at((uint8_t*)"{\"small\":123,\"neg\":-2,\"frac\":1.5,\"huge\":18446744073709551616}", 0u) == 0);
    assert(json_parser_ast_object_value_number_kind_at((uint8_t*)"{\"small\":123,\"neg\":-2,\"frac\":1.5,\"huge\":18446744073709551616}", 1u) == 1);
    assert(json_parser_ast_object_value_number_kind_at((uint8_t*)"{\"small\":123,\"neg\":-2,\"frac\":1.5,\"huge\":18446744073709551616}", 2u) == 2);
    assert(json_parser_ast_object_value_number_kind_at((uint8_t*)"{\"small\":123,\"neg\":-2,\"frac\":1.5,\"huge\":18446744073709551616}", 3u) == 3);
    assert(json_parser_ast_object_value_number_kind_at((uint8_t*)"{\"small\":123,\"neg\":-2,\"frac\":1.5,\"huge\":18446744073709551616}", 4u) < 0);
    assert(json_parser_ast_object_value_string_len_at((uint8_t*)"{\"name\":\"Ada\",\"smile\":\"\u263A\",\"ok\":true}", 0u) == 3);
    assert(json_parser_ast_object_value_string_len_at((uint8_t*)"{\"name\":\"Ada\",\"smile\":\"\u263A\",\"ok\":true}", 1u) == 3);
    assert(json_parser_ast_object_value_string_len_at((uint8_t*)"{\"name\":\"Ada\",\"smile\":\"\u263A\",\"ok\":true}", 2u) < 0);
    uint8_t object_value_buf[16] = {0};
    uint8_t object_value_small_buf[3] = {0};
    assert(json_parser_ast_object_value_string_copy_at((uint8_t*)"{\"name\":\"Ada\",\"smile\":\"\u263A\",\"ok\":true}", 0u, object_value_buf, sizeof(object_value_buf)) == 3);
    assert(strcmp((char*)object_value_buf, "Ada") == 0);
    assert(json_parser_ast_object_value_string_copy_at((uint8_t*)"{\"name\":\"Ada\",\"smile\":\"\u263A\",\"ok\":true}", 1u, object_value_buf, sizeof(object_value_buf)) == 3);
    assert(strcmp((char*)object_value_buf, "\xE2\x98\xBA") == 0);
    assert(json_parser_ast_object_value_string_copy_at((uint8_t*)"{\"name\":\"Ada\",\"smile\":\"\u263A\",\"ok\":true}", 1u, object_value_small_buf, sizeof(object_value_small_buf)) == 3);
    assert(json_parser_ast_object_value_string_copy_at((uint8_t*)"{\"name\":\"Ada\",\"smile\":\"\u263A\",\"ok\":true}", 2u, object_value_buf, sizeof(object_value_buf)) < 0);
    assert(json_parser_ast_array_i64_at((uint8_t*)"[4,5,6]", 1u, &array_root_second) == 1);
    assert(json_parser_ast_array_kind_at((uint8_t*)"[1,\"Ada\",false,null,[2],{\"ok\":true}]", 1u) == 3);
    assert(json_parser_ast_array_kind_at((uint8_t*)"[1,\"Ada\",false,null,[2],{\"ok\":true}]", 4u) == 4);
    assert(json_parser_ast_array_kind_at((uint8_t*)"[1,\"Ada\",false,null,[2],{\"ok\":true}]", 5u) == 5);
    assert(json_parser_ast_array_number_kind_at((uint8_t*)"[123,-2,1.5,18446744073709551616]", 0u) == 0);
    assert(json_parser_ast_array_number_kind_at((uint8_t*)"[123,-2,1.5,18446744073709551616]", 1u) == 1);
    assert(json_parser_ast_array_number_kind_at((uint8_t*)"[123,-2,1.5,18446744073709551616]", 2u) == 2);
    assert(json_parser_ast_array_number_kind_at((uint8_t*)"[123,-2,1.5,18446744073709551616]", 3u) == 3);
    assert(json_parser_ast_array_number_kind_at((uint8_t*)"[123,-2,1.5,18446744073709551616]", 4u) < 0);
    assert(json_parser_ast_array_string_len_at((uint8_t*)"[\"Ada\",\"\u263A\",true]", 0u) == 3);
    assert(json_parser_ast_array_string_len_at((uint8_t*)"[\"Ada\",\"\u263A\",true]", 1u) == 3);
    assert(json_parser_ast_array_string_len_at((uint8_t*)"[\"Ada\",\"\u263A\",true]", 2u) < 0);
    uint8_t array_value_buf[16] = {0};
    uint8_t array_value_small_buf[3] = {0};
    assert(json_parser_ast_array_string_copy_at((uint8_t*)"[\"Ada\",\"\u263A\",true]", 0u, array_value_buf, sizeof(array_value_buf)) == 3);
    assert(strcmp((char*)array_value_buf, "Ada") == 0);
    assert(json_parser_ast_array_string_copy_at((uint8_t*)"[\"Ada\",\"\u263A\",true]", 1u, array_value_buf, sizeof(array_value_buf)) == 3);
    assert(strcmp((char*)array_value_buf, "\xE2\x98\xBA") == 0);
    assert(json_parser_ast_array_string_copy_at((uint8_t*)"[\"Ada\",\"\u263A\",true]", 1u, array_value_small_buf, sizeof(array_value_small_buf)) == 3);
    assert(json_parser_ast_array_string_copy_at((uint8_t*)"[\"Ada\",\"\u263A\",true]", 2u, array_value_buf, sizeof(array_value_buf)) < 0);
    assert(json_parser_ast_array_array_len_at((uint8_t*)"[1,\"Ada\",false,null,[2,3],{\"ok\":true,\"n\":1}]", 4u) == 2);
    assert(json_parser_ast_array_object_len_at((uint8_t*)"[1,\"Ada\",false,null,[2,3],{\"ok\":true,\"n\":1}]", 5u) == 2);
    assert(json_parser_ast_array_object_len_at((uint8_t*)"[1,\"Ada\",false,null,[2,3],{\"ok\":true,\"n\":1}]", 1u) < 0);
    assert(json_parser_ast_array_string_eq_at((uint8_t*)"[\"Ada\",\"Bob\"]", 1u, (uint8_t*)"Bob") == 1);
    assert(json_parser_ast_array_bool_at((uint8_t*)"[false,true]", 1u) == 1);
    assert(json_parser_ast_array_is_null_at((uint8_t*)"[1,null,3]", 1u) == 1);
    assert(json_parser_ast_array_f64_at((uint8_t*)"[1.5,-2.25,1000.0]", 1u, &field_f64) == 1);
    assert(field_f64 == -2.25);
    assert(json_parser_ast_array_f32_at((uint8_t*)"[1.5,-2.25,1000.0]", 2u, &field_f32) == 1);
    assert(field_f32 == 1000.0f);
    assert(json_parser_ast_array_i64_at((uint8_t*)"[4,5,6]", 3u, &missing_num) == 0);
    assert(json_parser_ast_object_value_kind_at((uint8_t*)"{\"name\":\"Ada\",\"items\":[4,5],\"meta\":{\"ok\":true}}", 3u) < 0);
    assert(json_parser_ast_array_kind_at((uint8_t*)"[1,\"Ada\",false,null,[2],{\"ok\":true}]", 6u) < 0);
    assert(json_parser_ast_field_u64((uint8_t*)dom_doc, (uint8_t*)"big", &big_num) == 1);
    assert(json_parser_ast_field_i64((uint8_t*)dom_doc, (uint8_t*)"missing", &first_num) == 0);
    assert(first_num == 123);
    assert(second_num == -2);
    assert(object_second == 2);
    assert(array_root_second == 5);
    object_array_kind = json_parser_ast_object_value_kind_at((uint8_t*)"{\"name\":\"Ada\",\"items\":[4,5],\"meta\":{\"ok\":true}}", 1u);
    object_object_kind = json_parser_ast_object_value_kind_at((uint8_t*)"{\"name\":\"Ada\",\"items\":[4,5],\"meta\":{\"ok\":true}}", 2u);
    array_string_kind = json_parser_ast_array_kind_at((uint8_t*)"[1,\"Ada\",false,null,[2],{\"ok\":true}]", 1u);
    array_array_kind = json_parser_ast_array_kind_at((uint8_t*)"[1,\"Ada\",false,null,[2],{\"ok\":true}]", 4u);
    array_object_kind = json_parser_ast_array_kind_at((uint8_t*)"[1,\"Ada\",false,null,[2],{\"ok\":true}]", 5u);
    object_bool = json_parser_ast_object_field_bool_at((uint8_t*)"{\"name\":\"Ada\",\"ok\":true,\"none\":null}", 1u);
    object_null = json_parser_ast_object_field_is_null_at((uint8_t*)"{\"name\":\"Ada\",\"ok\":true,\"none\":null}", 2u);
    array_bool = json_parser_ast_array_bool_at((uint8_t*)"[false,true]", 1u);
    array_null = json_parser_ast_array_is_null_at((uint8_t*)"[1,null,3]", 1u);
    assert(object_array_kind == 4);
    assert(object_object_kind == 5);
    assert(array_string_kind == 3);
    assert(array_array_kind == 4);
    assert(array_object_kind == 5);
    assert(object_bool == 1);
    assert(object_null == 1);
    assert(array_bool == 1);
    assert(array_null == 1);
    assert(missing_num == 99);
    assert(big_num == UINT64_C(18446744073709551615));

    uint8_t owned_doc_src[] = "{\"name\":\"Ada\",\"nums\":[4,5],\"ok\":true,\"meta\":{\"note\":\"hi\"},\"none\":null,\"quote\":\"\\\"\"}";
    JsonParserDocument owned_doc = {0};
    JsonParserValue root_value = {0};
    JsonParserValue name_value = {0};
    JsonParserValue nums_value = {0};
    JsonParserValue second_value = {0};
    JsonParserValue meta_key_value = {0};
    JsonParserValue meta_value = {0};
    JsonParserValue note_value = {0};
    JsonParserValue missing_value = {0};
    JsonParserValue iter_key_value = {0};
    JsonParserValue iter_value_value = {0};
    JsonParserObjectIter root_object_iter = {0};
    JsonParserObjectIter next_object_iter = {0};
    JsonParserObjectIter third_object_iter = {0};
    JsonParserObjectIter fourth_object_iter = {0};
    JsonParserObjectIter fifth_object_iter = {0};
    uint8_t doc_name_buf[16] = {0};
    uint8_t doc_quote_buf[8] = {0};
    uint8_t doc_key_buf[16] = {0};
    uint8_t doc_value_buf[16] = {0};
    uint8_t value_buf[16] = {0};
    int64_t doc_num = 0;
    uint64_t doc_big = 0;
    JsonParserDocument float_handle = {0};
    JsonParserDocument float_array_doc = {0};
    JsonParserValue float_root_value = {0};
    JsonParserValue float_frac_value = {0};
    JsonParserValue float_huge_value = {0};
    JsonParserValue float_items_value = {0};
    JsonParserValue float_item_value = {0};
    JsonParserObjectIter float_object_iter = {0};
    JsonParserObjectIter float_next_object_iter = {0};
    JsonParserObjectIter float_third_object_iter = {0};
    JsonParserObjectIter float_fourth_object_iter = {0};
    JsonParserArrayIter float_items_iter = {0};
    JsonParserArrayIter float_items_next_iter = {0};
    assert(json_parser_document_parse(owned_doc_src, &owned_doc) == 1);
    assert(json_parser_document_checksum(&owned_doc) == json_parser_ast_checksum((uint8_t*)owned_doc_src));
    assert(json_parser_document_node_count(&owned_doc) > 0);
    assert(json_parser_document_root_kind(&owned_doc) == 5);
    assert(json_parser_document_object_len(&owned_doc) == 6);
    assert(json_parser_document_array_len(&owned_doc) < 0);
    owned_doc_src[2] = 'X';
    assert(json_parser_document_field_kind(&owned_doc, (uint8_t*)"name") == 3);
    assert(json_parser_document_field_bool(&owned_doc, (uint8_t*)"ok") == 1);
    assert(json_parser_document_field_is_null(&owned_doc, (uint8_t*)"missing") < 0);
    assert(json_parser_document_field_string_len(&owned_doc, (uint8_t*)"name") == 3);
    assert(json_parser_document_field_string_copy(&owned_doc, (uint8_t*)"name", doc_name_buf, sizeof(doc_name_buf)) == 3);
    assert(strcmp((char*)doc_name_buf, "Ada") == 0);
    assert(json_parser_document_field_string_copy(&owned_doc, (uint8_t*)"quote", doc_quote_buf, sizeof(doc_quote_buf)) == 1);
    assert(strcmp((char*)doc_quote_buf, "\"") == 0);
    assert(json_parser_document_array_field_len(&owned_doc, (uint8_t*)"nums") == 2);
    assert(json_parser_document_object_field_len(&owned_doc, (uint8_t*)"meta") == 1);
    assert(json_parser_document_array_field_i64_at(&owned_doc, (uint8_t*)"nums", 1u, &doc_num) == 1);
    assert(doc_num == 5);
    assert(json_parser_document_array_field_kind_at(&owned_doc, (uint8_t*)"nums", 0u) == 2);
    assert(json_parser_document_object_key_len_at(&owned_doc, 0u) == 4);
    assert(json_parser_document_object_key_copy_at(&owned_doc, 3u, doc_key_buf, sizeof(doc_key_buf)) == 4);
    assert(strcmp((char*)doc_key_buf, "meta") == 0);
    assert(json_parser_document_object_value_kind_at(&owned_doc, 3u) == 5);
    assert(json_parser_document_object_value_string_copy_at(&owned_doc, 5u, doc_value_buf, sizeof(doc_value_buf)) == 1);
    assert(strcmp((char*)doc_value_buf, "\"") == 0);
    assert(json_parser_document_field_u64(&owned_doc, (uint8_t*)"big", &doc_big) == 0);
    assert(json_parser_document_root_value(&owned_doc, &root_value) == 1);
    assert(json_parser_value_is_valid(&root_value) == 1);
    assert(json_parser_value_kind(&root_value) == 5);
    assert(json_parser_value_object_len(&root_value) == 6);
    assert(json_parser_value_array_len(&root_value) < 0);
    assert(json_parser_value_field(&root_value, (uint8_t*)"name", &name_value) == 1);
    assert(json_parser_value_field_kind(&root_value, (uint8_t*)"name") == 3);
    assert(json_parser_value_field_string_len(&root_value, (uint8_t*)"name") == 3);
    assert(json_parser_value_field_string_eq(&root_value, (uint8_t*)"name", (uint8_t*)"Ada") == 1);
    assert(json_parser_value_string_len(&name_value) == 3);
    assert(json_parser_value_string_eq(&name_value, (uint8_t*)"Ada") == 1);
    assert(json_parser_value_string_copy(&name_value, value_buf, sizeof(value_buf)) == 3);
    assert(strcmp((char*)value_buf, "Ada") == 0);
    assert(json_parser_value_field_bool(&root_value, (uint8_t*)"ok") == 1);
    assert(json_parser_value_field(&root_value, (uint8_t*)"nums", &nums_value) == 1);
    assert(json_parser_value_kind(&nums_value) == 4);
    assert(json_parser_value_array_len(&nums_value) == 2);
    assert(json_parser_value_field_array_len(&root_value, (uint8_t*)"nums") == 2);
    assert(json_parser_value_field_object_len(&root_value, (uint8_t*)"meta") == 1);
    assert(json_parser_value_index_kind(&nums_value, 0u) == 2);
    assert(json_parser_value_index(&nums_value, 1u, &second_value) == 1);
    assert(json_parser_value_number_kind(&second_value) == 0);
    assert(json_parser_value_index_number_kind(&nums_value, 1u) == 0);
    assert(json_parser_value_i64(&second_value, &doc_num) == 1);
    assert(json_parser_value_index_i64(&nums_value, 1u, &doc_num) == 1);
    assert(doc_num == 5);
    assert(json_parser_value_object_key_at(&root_value, 3u, &meta_key_value) == 1);
    assert(json_parser_value_string_copy(&meta_key_value, value_buf, sizeof(value_buf)) == 4);
    assert(strcmp((char*)value_buf, "meta") == 0);
    assert(json_parser_value_object_value_at(&root_value, 3u, &meta_value) == 1);
    assert(json_parser_value_kind(&meta_value) == 5);
    assert(json_parser_value_field(&meta_value, (uint8_t*)"note", &note_value) == 1);
    assert(json_parser_value_string_copy(&note_value, value_buf, sizeof(value_buf)) == 2);
    assert(strcmp((char*)value_buf, "hi") == 0);
    assert(json_parser_value_object_iter(&root_value, &root_object_iter) == 1);
    assert(json_parser_object_iter_is_valid(&root_object_iter) == 1);
    assert(json_parser_object_iter_key_string_eq(&root_object_iter, (uint8_t*)"name") == 1);
    assert(json_parser_object_iter_key_string_len(&root_object_iter) == 4);
    assert(json_parser_object_iter_key_string_copy(&root_object_iter, value_buf, sizeof(value_buf)) == 4);
    assert(strcmp((char*)value_buf, "name") == 0);
    assert(json_parser_object_iter_value_kind(&root_object_iter) == 3);
    assert(json_parser_object_iter_value_string_eq(&root_object_iter, (uint8_t*)"Ada") == 1);
    assert(json_parser_object_iter_value_string_len(&root_object_iter) == 3);
    assert(json_parser_object_iter_value_string_copy(&root_object_iter, value_buf, sizeof(value_buf)) == 3);
    assert(strcmp((char*)value_buf, "Ada") == 0);
    assert(json_parser_object_iter_key(&root_object_iter, &iter_key_value) == 1);
    assert(json_parser_value_string_copy(&iter_key_value, value_buf, sizeof(value_buf)) == 4);
    assert(strcmp((char*)value_buf, "name") == 0);
    assert(json_parser_object_iter_value(&root_object_iter, &iter_value_value) == 1);
    assert(json_parser_value_string_copy(&iter_value_value, value_buf, sizeof(value_buf)) == 3);
    assert(strcmp((char*)value_buf, "Ada") == 0);
    assert(json_parser_object_iter_next(&root_object_iter, &next_object_iter) == 1);
    assert(json_parser_object_iter_key_string_eq(&next_object_iter, (uint8_t*)"nums") == 1);
    assert(json_parser_object_iter_value_kind(&next_object_iter) == 4);
    assert(json_parser_object_iter_value_array_len(&next_object_iter) == 2);
    assert(json_parser_object_iter_key(&next_object_iter, &iter_key_value) == 1);
    assert(json_parser_value_string_copy(&iter_key_value, value_buf, sizeof(value_buf)) == 4);
    assert(strcmp((char*)value_buf, "nums") == 0);
    assert(json_parser_object_iter_next(&next_object_iter, &third_object_iter) == 1);
    assert(json_parser_object_iter_key_string_eq(&third_object_iter, (uint8_t*)"ok") == 1);
    assert(json_parser_object_iter_value_bool(&third_object_iter) == 1);
    assert(json_parser_object_iter_next(&third_object_iter, &fourth_object_iter) == 1);
    assert(json_parser_object_iter_key_string_eq(&fourth_object_iter, (uint8_t*)"meta") == 1);
    assert(json_parser_object_iter_value_object_len(&fourth_object_iter) == 1);
    assert(json_parser_object_iter_next(&fourth_object_iter, &fifth_object_iter) == 1);
    assert(json_parser_object_iter_key_string_eq(&fifth_object_iter, (uint8_t*)"none") == 1);
    assert(json_parser_object_iter_value_is_null(&fifth_object_iter) == 1);
    assert(json_parser_value_field(&root_value, (uint8_t*)"missing", &missing_value) == 0);
    assert(json_parser_value_field_kind(&root_value, (uint8_t*)"missing") < 0);
    assert(json_parser_value_is_valid(&missing_value) == 0);
    assert(json_parser_document_destroy(owned_doc.impl_bits) == 1);
    owned_doc.impl_bits = 0;
    assert(json_parser_document_destroy(owned_doc.impl_bits) == 0);

    assert(json_parser_document_parse((uint8_t*)float_doc, &float_handle) == 1);
    assert(json_parser_document_field_f64(&float_handle, (uint8_t*)"frac", &field_f64) == 1);
    assert(field_f64 == 1.5);
    assert(json_parser_document_field_f32(&float_handle, (uint8_t*)"exp", &field_f32) == 1);
    assert(field_f32 == 1000.0f);
    assert(json_parser_document_array_field_f64_at(&float_handle, (uint8_t*)"items", 0u, &field_f64) == 1);
    assert(field_f64 == -2.25);
    assert(json_parser_document_array_field_f32_at(&float_handle, (uint8_t*)"items", 1u, &field_f32) == 1);
    assert(field_f32 == 1000.0f);
    assert(json_parser_document_object_field_f64_at(&float_handle, 2u, &field_f64) == 1);
    assert(field_f64 == 18446744073709551616.0);
    assert(json_parser_document_object_field_f32_at(&float_handle, 1u, &field_f32) == 1);
    assert(field_f32 == 1000.0f);
    assert(json_parser_document_root_value(&float_handle, &float_root_value) == 1);
    assert(json_parser_value_field(&float_root_value, (uint8_t*)"frac", &float_frac_value) == 1);
    assert(json_parser_value_f64(&float_frac_value, &field_f64) == 1);
    assert(field_f64 == 1.5);
    assert(json_parser_value_field_f64(&float_root_value, (uint8_t*)"frac", &field_f64) == 1);
    assert(field_f64 == 1.5);
    assert(json_parser_value_field(&float_root_value, (uint8_t*)"huge", &float_huge_value) == 1);
    assert(json_parser_value_f32(&float_huge_value, &field_f32) == 1);
    assert(field_f32 > 1.0e19f);
    assert(json_parser_value_field_f32(&float_root_value, (uint8_t*)"exp", &field_f32) == 1);
    assert(field_f32 == 1000.0f);
    assert(json_parser_value_field(&float_root_value, (uint8_t*)"items", &float_items_value) == 1);
    assert(json_parser_value_object_iter(&float_root_value, &float_object_iter) == 1);
    assert(json_parser_object_iter_key_string_eq(&float_object_iter, (uint8_t*)"frac") == 1);
    assert(json_parser_object_iter_value_number_kind(&float_object_iter) == 2);
    assert(json_parser_object_iter_value_f64(&float_object_iter, &field_f64) == 1);
    assert(field_f64 == 1.5);
    assert(json_parser_object_iter_next(&float_object_iter, &float_next_object_iter) == 1);
    assert(json_parser_object_iter_key_string_eq(&float_next_object_iter, (uint8_t*)"exp") == 1);
    assert(json_parser_object_iter_value_f32(&float_next_object_iter, &field_f32) == 1);
    assert(field_f32 == 1000.0f);
    assert(json_parser_object_iter_next(&float_next_object_iter, &float_third_object_iter) == 1);
    assert(json_parser_object_iter_key_string_eq(&float_third_object_iter, (uint8_t*)"huge") == 1);
    assert(json_parser_object_iter_value_f64(&float_third_object_iter, &field_f64) == 1);
    assert(field_f64 == 18446744073709551616.0);
    assert(json_parser_object_iter_next(&float_third_object_iter, &float_fourth_object_iter) == 1);
    assert(json_parser_object_iter_key_string_eq(&float_fourth_object_iter, (uint8_t*)"items") == 1);
    assert(json_parser_object_iter_value_kind(&float_fourth_object_iter) == 4);
    assert(json_parser_object_iter_value_array_len(&float_fourth_object_iter) == 2);
    assert(json_parser_value_index(&float_items_value, 0u, &float_item_value) == 1);
    assert(json_parser_value_f64(&float_item_value, &field_f64) == 1);
    assert(field_f64 == -2.25);
    assert(json_parser_value_index_f64(&float_items_value, 0u, &field_f64) == 1);
    assert(field_f64 == -2.25);
    assert(json_parser_value_index(&float_items_value, 1u, &float_item_value) == 1);
    assert(json_parser_value_f32(&float_item_value, &field_f32) == 1);
    assert(field_f32 == 1000.0f);
    assert(json_parser_value_index_f32(&float_items_value, 1u, &field_f32) == 1);
    assert(field_f32 == 1000.0f);
    assert(json_parser_value_array_iter(&float_items_value, &float_items_iter) == 1);
    assert(json_parser_array_iter_kind(&float_items_iter) == 2);
    assert(json_parser_array_iter_number_kind(&float_items_iter) == 2);
    assert(json_parser_array_iter_f64(&float_items_iter, &field_f64) == 1);
    assert(field_f64 == -2.25);
    assert(json_parser_array_iter_next(&float_items_iter, &float_items_next_iter) == 1);
    assert(json_parser_array_iter_kind(&float_items_next_iter) == 2);
    assert(json_parser_array_iter_f32(&float_items_next_iter, &field_f32) == 1);
    assert(field_f32 == 1000.0f);
    assert(json_parser_document_parse((uint8_t*)"[1.5,-2.25,1000.0]", &float_array_doc) == 1);
    assert(json_parser_document_array_f64_at(&float_array_doc, 1u, &field_f64) == 1);
    assert(field_f64 == -2.25);
    assert(json_parser_document_array_f32_at(&float_array_doc, 2u, &field_f32) == 1);
    assert(field_f32 == 1000.0f);
    assert(json_parser_document_destroy(float_array_doc.impl_bits) == 1);
    float_array_doc.impl_bits = 0;
    assert(json_parser_document_destroy(float_handle.impl_bits) == 1);
    float_handle.impl_bits = 0;

    JsonParserDocument array_doc = {0};
    JsonParserValue array_root_value = {0};
    JsonParserValue array_string_value = {0};
    JsonParserValue nested_array_value = {0};
    JsonParserValue nested_object_value = {0};
    JsonParserValue nested_ok_value = {0};
    JsonParserValue array_iter_value = {0};
    JsonParserArrayIter array_iter = {0};
    JsonParserArrayIter next_array_iter = {0};
    uint8_t array_doc_buf[16] = {0};
    assert(json_parser_document_parse((uint8_t*)"[4,\"Ada\",false,null,[1,2],{\"ok\":true}]", &array_doc) == 1);
    assert(json_parser_document_root_kind(&array_doc) == 4);
    assert(json_parser_document_array_len(&array_doc) == 6);
    assert(json_parser_document_object_len(&array_doc) < 0);
    assert(json_parser_document_array_i64_at(&array_doc, 0u, &doc_num) == 1);
    assert(doc_num == 4);
    assert(json_parser_document_array_kind_at(&array_doc, 1u) == 3);
    assert(json_parser_document_array_string_copy_at(&array_doc, 1u, array_doc_buf, sizeof(array_doc_buf)) == 3);
    assert(strcmp((char*)array_doc_buf, "Ada") == 0);
    assert(json_parser_document_root_value(&array_doc, &array_root_value) == 1);
    assert(json_parser_value_kind(&array_root_value) == 4);
    assert(json_parser_value_index_string_eq(&array_root_value, 1u, (uint8_t*)"Ada") == 1);
    assert(json_parser_value_index(&array_root_value, 1u, &array_string_value) == 1);
    assert(json_parser_value_string_copy(&array_string_value, value_buf, sizeof(value_buf)) == 3);
    assert(strcmp((char*)value_buf, "Ada") == 0);
    assert(json_parser_value_index(&array_root_value, 4u, &nested_array_value) == 1);
    assert(json_parser_value_array_len(&nested_array_value) == 2);
    assert(json_parser_value_index_array_len(&array_root_value, 4u) == 2);
    assert(json_parser_value_index(&array_root_value, 5u, &nested_object_value) == 1);
    assert(json_parser_value_object_len(&nested_object_value) == 1);
    assert(json_parser_value_index_object_len(&array_root_value, 5u) == 1);
    assert(json_parser_value_field(&nested_object_value, (uint8_t*)"ok", &nested_ok_value) == 1);
    assert(json_parser_value_bool(&nested_ok_value) == 1);
    assert(json_parser_value_array_iter(&array_root_value, &array_iter) == 1);
    assert(json_parser_array_iter_is_valid(&array_iter) == 1);
    assert(json_parser_array_iter_kind(&array_iter) == 2);
    assert(json_parser_array_iter_number_kind(&array_iter) == 0);
    assert(json_parser_array_iter_i64(&array_iter, &doc_num) == 1);
    assert(doc_num == 4);
    assert(json_parser_array_iter_u64(&array_iter, &doc_big) == 1);
    assert(doc_big == 4u);
    assert(json_parser_array_iter_value(&array_iter, &array_iter_value) == 1);
    assert(json_parser_value_i64(&array_iter_value, &doc_num) == 1);
    assert(doc_num == 4);
    assert(json_parser_array_iter_next(&array_iter, &next_array_iter) == 1);
    assert(json_parser_array_iter_string_eq(&next_array_iter, (uint8_t*)"Ada") == 1);
    assert(json_parser_array_iter_string_len(&next_array_iter) == 3);
    assert(json_parser_array_iter_string_copy(&next_array_iter, value_buf, sizeof(value_buf)) == 3);
    assert(strcmp((char*)value_buf, "Ada") == 0);
    assert(json_parser_array_iter_value(&next_array_iter, &array_iter_value) == 1);
    assert(json_parser_value_string_copy(&array_iter_value, value_buf, sizeof(value_buf)) == 3);
    assert(strcmp((char*)value_buf, "Ada") == 0);
    JsonParserArrayIter third_array_iter = {0};
    JsonParserArrayIter fourth_array_iter = {0};
    JsonParserArrayIter fifth_array_iter = {0};
    JsonParserArrayIter sixth_array_iter = {0};
    assert(json_parser_array_iter_next(&next_array_iter, &third_array_iter) == 1);
    assert(json_parser_array_iter_bool(&third_array_iter) == 0);
    assert(json_parser_array_iter_next(&third_array_iter, &fourth_array_iter) == 1);
    assert(json_parser_array_iter_is_null(&fourth_array_iter) == 1);
    assert(json_parser_array_iter_next(&fourth_array_iter, &fifth_array_iter) == 1);
    assert(json_parser_array_iter_kind(&fifth_array_iter) == 4);
    assert(json_parser_array_iter_array_len(&fifth_array_iter) == 2);
    assert(json_parser_array_iter_next(&fifth_array_iter, &sixth_array_iter) == 1);
    assert(json_parser_array_iter_kind(&sixth_array_iter) == 5);
    assert(json_parser_array_iter_object_len(&sixth_array_iter) == 1);
    assert(json_parser_document_destroy(array_doc.impl_bits) == 1);
    array_doc.impl_bits = 0;

    assert(json_parser_parallel_max_workers() >= 1);
    assert(json_parser_parallel_checksum((uint8_t*)"[1,2,3]", 1u, 3u) == 345);
    assert(json_parser_parallel_checksum((uint8_t*)"[1,2,3]", 4u, 5u) == 575);
    assert(json_parser_parallel_ast_checksum((uint8_t*)"{\"a\":1}", 2u, 4u) == 356);
    assert(json_parser_parallel_ast_cached_checksum((uint8_t*)"{\"items\":[1,2,3],\"ok\":true}", 3u, 2u) == 468);
    assert(json_parser_parallel_checksum((uint8_t*)"{\"a\":[1,2}", 2u, 4u) < 0);

    return 0;
}
