package main

import (
	"bytes"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunCLICompilesFixtureProgramsToLLVM(t *testing.T) {
	repoRoot := repoRootFromMainTest(t)
	fixtures := []struct {
		name   string
		path   string
		checks []string
	}{
		{
			name: "pointer_alloc",
			path: filepath.Join(repoRoot, "Code", "test_programs", "pointer_alloc.elisa"),
			checks: []string{
				"%ErrUnion__MemoryError__heap_Node = type { i32, ptr }",
				"%ErrUnion__MemoryError__int = type { i32, i64 }",
				"%Node = type { i64, ptr }",
				"declare ptr @alloc_node()",
				"declare ptr @sfree_node(ptr)",
				"define i32 @require_node(ptr ",
				"define i32 @make_node_value(ptr ",
				"define i64 @make_node_value_or_zero()",
				"define void @release_node(ptr",
			},
		},
		{
			name: "shape_ops",
			path: filepath.Join(repoRoot, "Code", "test_programs", "shape_ops.elisa"),
			checks: []string{
				"%ErrUnion__ShapeOpError__",
				"%DynArray__i32 = type { ptr, i64, i64 }",
				"declare i32 @resize(",
				"declare i32 @push(",
				"define i32 @grow_once(",
				"define i32 @merge_strings(",
			},
		},
		{
			name: "variadic_stdio",
			path: filepath.Join(repoRoot, "Code", "test_programs", "variadic_stdio.elisa"),
			checks: []string{
				"%ErrUnion__FormatError__int = type { i32, i64 }",
				"declare i64 @snprintf(ptr, i64, ptr, ...)",
				"define i32 @checked_format_len(",
				"define i64 @format_len(ptr",
				"define i32 @checked_write_into(",
				"define i64 @write_into(ptr %0, i64 %1, ptr %2)",
				"call i64 (ptr, i64, ptr, ...) @snprintf(",
			},
		},
		{
			name: "allocator_ownership",
			path: filepath.Join(repoRoot, "Code", "test_programs", "allocator_ownership.elisa"),
			checks: []string{
				"%HeapPairNode = type { %FuzzPair, ptr }",
				"declare ptr @alloc_heap_pair_node()",
				"declare ptr @sfree_heap_pair_node(ptr)",
				"declare ptr @alloc_bytes(i64)",
				"declare ptr @sfree_bytes(ptr)",
				"declare i64 @snprintf(ptr, i64, ptr, ...)",
				"define i32 @build_pair_chain_sum(ptr ",
				"define i32 @borrow_then_release_single_pair(ptr ",
				"@recursive_format_or_fallback(",
				"@allocator_ownership_combo(",
			},
		},
		{
			name: "pointer_casts",
			path: filepath.Join(repoRoot, "Code", "test_programs", "pointer_casts.elisa"),
			checks: []string{
				"define i64 @ptr_bits(ptr",
				"ptrtoint ptr",
				"define ptr @bits_ptr(i64",
				"inttoptr i64",
				"define ptr @advance_raw(ptr %0, i64 %1)",
				"getelementptr i8, ptr",
			},
		},
		{
			name: "stack_pointers",
			path: filepath.Join(repoRoot, "Code", "test_programs", "stack_pointers.elisa"),
			checks: []string{
				"%ErrUnion__StackError__int = type { i32, i64 }",
				"%ScratchSlot = type { i64 }",
				"define i32 @checked_stack_slot(ptr",
				"define i64 @stack_slot_or_zero()",
				"alloca %ScratchSlot",
			},
		},
		{
			name: "nested_access",
			path: filepath.Join(repoRoot, "Code", "test_programs", "nested_access.elisa"),
			checks: []string{
				"declare %DynArray__i32 @make_array()",
				"declare %DynArrayView @make_array_view()",
				"call %DynArray__i32 @make_array()",
				"call %DynArrayView @make_array_view()",
				"darrayslice.view.len.out = sub i64",
				"getelementptr i8, ptr",
				"extractvalue %DynArray__i32",
				"alloca %DynArray__i32",
				"alloca %DynArrayView",
			},
		},
		{
			name: "typed_list_views",
			path: filepath.Join(repoRoot, "Code", "test_programs", "typed_list_views.elisa"),
			checks: []string{
				"define i32 @head_of_middle(%DynArray__i32",
				"darrayslice.view.len.out = sub i64",
				"getelementptr i8, ptr",
				"extractvalue %DynArray__i32",
				"define i64 @inferred_literal_head()",
				"alloca [4 x i64]",
				"getelementptr [4 x i64], ptr",
				"insertvalue %DynArrayView",
			},
		},
		{
			name: "string_view_ops",
			path: filepath.Join(repoRoot, "Code", "test_programs", "string_view_ops.elisa"),
			checks: []string{
				"%StringView = type { ptr, i64 }",
				"declare %StringView @ctx_string_view(ptr, i64, i64)",
				"call %StringView @ctx_string_view(ptr",
				"declare i64 @ctx_string_view_index(%StringView, i64)",
				"declare i64 @ctx_strlen(ptr)",
				"declare i64 @ctx_string_view_eq(%StringView, ptr)",
				"declare i64 @ctx_string_views_eq(%StringView, %StringView)",
			},
		},
		{
			name: "export_vec2i",
			path: filepath.Join(repoRoot, "Code", "test_programs", "export_vec2i.elisa"),
			checks: []string{
				"define %Vec__i32 @vec_add_i32(%Vec__i32",
				"define %Vec__i32 @keep_left__Vec_i32(%Vec__i32",
				"define i64 @vec2i_add(i64",
				"define i64 @vec2i_keep_left(i64",
			},
		},
		{
			name: "dict_runtime",
			path: filepath.Join(repoRoot, "Code", "test_programs", "dict_runtime.elisa"),
			checks: []string{
				"%DynDict__cstr_key_shape__i32 = type { ptr, i64, i64, i64, ptr }",
				"%ErrUnion__RuntimeError__i32 = type { i32, ptr }",
				"define %DynDict__cstr_key_shape__i32 @arena_dict_new__i32(",
				"define i32 @arena_dict_reserve__i32(",
				"define ptr @arena_dict_get__i32(",
				"define i32 @arena_dict_put__i32(",
				"define i1 @arena_dict_contains__i32(",
				"define i1 @arena_dict_remove__i32(",
				"define void @arena_dict_clear__i32(",
				"define i32 @touch_dict(ptr ",
				"call %DynDict__cstr_key_shape__i32 @arena_dict_new__i32(ptr",
				"call i32 @arena_dict_put__i32(ptr",
			},
		},
		{
			name: "stable_symbol_table",
			path: filepath.Join(repoRoot, "Code", "test_programs", "stable_symbol_table.elisa"),
			checks: []string{
				"%SymbolTable__cstr_key_shape__FixtureSymbol = type",
				"%IndexMap__cstr_key_shape__FixtureSymbol = type",
				"%IndexMapEntry__cstr_key_shape__FixtureSymbol = type",
				"%SymbolEntry__cstr_key_shape__FixtureSymbol = type",
				"%Optional__FixtureSymbol = type",
				"%Optional__usize = type",
				"@indexmap = global %IndexMapNamespace",
				"@symtab = global %SymbolTableNamespace",
				"define i32 @stable_symbol_table_smoke(ptr",
				"define i32 @stable_symbol_table_default_capacity(ptr",
				"define i32 @stable_index_map_smoke(ptr",
				"define %IndexMap__cstr_key_shape__FixtureSymbol @index_map_new__cstr_key_shape__FixtureSymbol(",
				"define i64 @index_map_set__cstr_key_shape__FixtureSymbol(",
				"define %Optional__FixtureSymbol @index_map_get__cstr_key_shape__FixtureSymbol(",
				"define i1 @index_map_has__cstr_key_shape__FixtureSymbol(",
				"define %SymbolTable__cstr_key_shape__FixtureSymbol @ovl__with_capacity__",
				"define %SymbolTable__cstr_key_shape__FixtureSymbol @ovl__new__",
				"define i32 @declare__cstr_key_shape__FixtureSymbol(",
				"define i1 @update__cstr_key_shape__FixtureSymbol(",
				"define %Optional__FixtureSymbol @lookup__cstr_key_shape__FixtureSymbol(",
				"define i32 @lookup_id__cstr_key_shape__FixtureSymbol(",
				"define i64 @set__cstr_key_shape__FixtureSymbol(",
				"define i1 @ovl__has__semantic_RefType_SymbolTable_K_T__has__cstr_key_shape__FixtureSymbol(",
				"define i64 @ovl__count__semantic_RefType_SymbolTable_K_T__count__cstr_key_shape__FixtureSymbol(",
				"define %Optional__FixtureSymbol @get__cstr_key_shape__FixtureSymbol(",
				"call i32 @declare__cstr_key_shape__FixtureSymbol(",
			},
		},
		{
			name: "inline_vec",
			path: filepath.Join(repoRoot, "Code", "test_programs", "inline_vec.elisa"),
			checks: []string{
				"%InlineVec__i32__4 = type { ptr, [4 x i32], %DynArray__i32, i64, i1 }",
				"%InlineVec__i32__8 = type { ptr, [8 x i32], %DynArray__i32, i64, i1 }",
				"@inlinevec = global %InlineVecNamespace",
				"define i32 @inline_vec4_inline_smoke(ptr",
				"define i32 @inline_vec4_spill_smoke(ptr",
				"define i32 @inline_vec8_view_smoke(ptr",
				"define i32 @inline_vec_clear_smoke(ptr",
				"define i32 @inline_vec_pop_last_smoke(ptr",
				"define %InlineVec__i32__4 @inline_vec__i32__4(",
				"define %InlineVec__i32__8 @inline_vec__i32__8(",
				"define void @inline_vec_push__i32__4(",
				"define void @inline_vec_push__i32__8(",
				"define i32 @inline_vec_get__i32__4(",
				"define void @inline_vec_set__i32__4(",
				"define i1 @inline_vec_is_empty__i32__4(",
				"define i32 @inline_vec_pop__i32__4(",
				"define i32 @inline_vec_last__i32__4(",
				"define %DynArrayView @inline_vec_view__i32__8(",
				"call void @inline_vec_push__i32__4(",
				"call %DynArrayView @inline_vec_view__i32__8(",
			},
		},
		{
			name: "interned_names",
			path: filepath.Join(repoRoot, "Code", "test_programs", "interned_names.elisa"),
			checks: []string{
				"define i32 @interned_name_methods_smoke(ptr",
				"call i32 @__ovl__intern__",
				"call i32 @__ovl__intern_ci__",
				"call i1 @__ovl__valid_id__",
				"call i1 @__ovl__has_text_cs__",
				"call i1 @__ovl__has_text_ci__",
				"call %StringView @__ovl__text__",
			},
		},
		{
			name: "array_builders",
			path: filepath.Join(repoRoot, "Code", "test_programs", "array_builders.elisa"),
			checks: []string{
				"%DArrayBuilder__i32 = type { ptr, %DynArray__i32 }",
				"@arraybuilder = global %DArrayBuilderNamespace",
				"define i32 @array_builder_smoke(ptr",
				"define i32 @array_builder_clear_smoke(ptr",
				"define %DArrayBuilder__i32 @darray_builder__i32(",
				"define void @darray_builder_push__i32(",
				"define i32 @darray_builder_get__i32(",
				"define %DynArray__i32 @darray_builder_finish__i32(",
				"call void @ovl__push__semantic_RefType_mutable_DArrayBuilder_T__push__i32(",
				"call i32 @ovl__get__semantic_RefType_DArrayBuilder_T__get__i32(",
				"call %DynArray__i32 @ovl__finish__semantic_RefType_DArrayBuilder_T__finish__i32(",
			},
		},
		{
			name: "frontend_lexer",
			path: filepath.Join(repoRoot, "Code", "test_programs", "frontend_lexer.elisa"),
			checks: []string{
				"%FrontendPos = type { i64, i64, i64 }",
				"%FrontendToken = type { i32, %FrontendPos, %StringView, %StringView }",
				"define i64 @frontend_advance_char(ptr",
				"define %FrontendToken @frontend_next_token(ptr",
				"define %DynArray__FrontendToken @frontend_tokenize(ptr",
				"define i64 @frontend_lexer_parity_suite()",
				"define i64 @frontend_lexer_token_count(ptr ",
				"define i64 @frontend_lexer_token_checksum(ptr ",
				"define i64 @frontend_lexer_token_kind_at(ptr ",
				"define i64 @frontend_lexer_copy_token_kinds(ptr ",
			},
		},
		{
			name: "compiler_parallel_fixture",
			path: filepath.Join(repoRoot, "Code", "test_programs", "compiler_parallel_fixture.elisa"),
			checks: []string{
				"%Expr = type { i32, i64, [1 x i64] }",
				"%FrozenExprGraph = type { %Expr__Store, i32 }",
				"%Thread__i64__Joinable = type { i64, ptr }",
				"%Task__i64__Pending = type { i64, ptr }",
				"define %FrozenExprGraph @build_frozen_expr_graph(",
				"define i64 @expr_sum(%FrozenExprGraph",
				"define i64 @expr_depth(%FrozenExprGraph",
				"define i64 @compiler_parallel_fixture(ptr",
				"define %Thread__i64__Joinable @spawn1__FrozenExprGraph__i64(",
				"define %Task__i64__Pending @pool_submit1__FrozenExprGraph__i64(",
				"define void @task_group_add__i64(",
				"call i64 @join__i64(",
				"call i64 @pool_await__i64(",
			},
		},
		{
			name: "frontend_stress",
			path: filepath.Join(repoRoot, "Code", "test_programs", "frontend_stress.elisa"),
			checks: []string{
				"%SourceSpan = type { i64, i64 }",
				"%Token = type { i32, %SourceSpan, ptr }",
				"%DynDict__cstr__Symbol = type { ptr, i64, i64, i64, ptr }",
				"%Scope = type { ptr, %DynDict__cstr__Symbol, i64 }",
				"%ParserState = type { %DynArrayView, i64, ptr }",
				"define %DynArrayView @make_tokens()",
				"define i32 @frontend_scope_stress(ptr",
				"define i64 @frontend_region_token(i64",
				"define i32 @frontend_smoke(ptr",
				"define %DynDict__cstr__Symbol @arena_dict_new__Symbol(ptr",
				"define i32 @arena_dict_put__Symbol(ptr",
				"define i1 @arena_dict_contains__Symbol(ptr",
				"call ptr @new_region(i64 2048)",
				"call ptr @arena_alloc(ptr",
			},
		},
		{
			name: "recursive_enum",
			path: filepath.Join(repoRoot, "Code", "test_programs", "recursive_enum.elisa"),
			checks: []string{
				"%Expr = type { i32, [2 x i64] }",
				"define i64 @eval(ptr",
				"define i64 @make_sum()",
				"call ptr @arena_alloc(ptr",
				"call i64 @eval(ptr",
			},
		},
		{
			name: "regular_enum_values",
			path: filepath.Join(repoRoot, "Code", "test_programs", "regular_enum_values.elisa"),
			checks: []string{
				"%Small = type { i32, [2 x i64] }",
				"define %Small @make_node(i64",
				"define i64 @score(%Small",
				"define i64 @total(i64",
				"define i64 @main()",
			},
		},
		{
			name: "region_checkpoints",
			path: filepath.Join(repoRoot, "Code", "test_programs", "region_checkpoints.elisa"),
			checks: []string{
				"%Arena = type { ptr, ptr, i64 }",
				"%ArenaMark = type { ptr, i64 }",
				"declare %ArenaMark @arena_snapshot(ptr)",
				"declare void @arena_rewind(ptr, %ArenaMark)",
				"declare void @arena_reset(ptr)",
				"call %ArenaMark @arena_snapshot(ptr",
				"call void @arena_rewind(ptr",
				"call void @arena_reset(ptr",
			},
		},
		{
			name: "region_ref_types",
			path: filepath.Join(repoRoot, "Code", "test_programs", "region_ref_types.elisa"),
			checks: []string{
				"%RegionNode__scratch = type { ptr, i32 }",
				"define i32 @region_ref_sum(i32 ",
				"call ptr @arena_alloc(ptr",
				"load i32, ptr",
			},
		},
		{
			name: "packed_enum_common",
			path: filepath.Join(repoRoot, "Code", "test_programs", "packed_enum_common.elisa"),
			checks: []string{
				"%Expr = type { i32, i64, [1 x i64] }",
				"%Token = type { i32, i64 }",
				"define i32 @build_expr(%Arena",
				"define i64 @eval(i32",
				"define i64 @packed_demo()",
				"load i64, ptr",
			},
		},
		{
			name: "ref_qualifier_generics",
			path: filepath.Join(repoRoot, "Code", "test_programs", "ref_qualifier_generics.elisa"),
			checks: []string{
				"%Handle__heap__anon = type { ptr }",
				"define %Handle__heap__anon @keep_handle__heap__anon(%Handle__heap__anon",
				"define i32 @peek_value(%Handle__heap__anon",
				"define i64 @keep_heap_handle(i64",
				"call %Handle__heap__anon @keep_handle__heap__anon(%Handle__heap__anon",
				"define i32 @peek_heap_value(i64",
			},
		},
		{
			name: "json_parser",
			path: filepath.Join(repoRoot, "Code", "test_programs", "json_parser.elisa"),
			checks: []string{
				"%JsonCursor = type { ptr, i64, i64 }",
				"%JsonLexemeResult = type { i64, i64, i64 }",
				"%JsonNode = type { i32, [2 x i64] }",
				"%JsonParseNodeResult = type { i32, i64 }",
				"define %JsonLexemeResult @json_parse_string_lexeme(ptr",
				"define %JsonLexemeResult @json_parse_number_lexeme(ptr",
				"define i64 @json_parse_string(ptr",
				"define i64 @json_parse_number(ptr",
				"define i64 @json_parse_array(ptr",
				"define i64 @json_parse_object(ptr",
				"define %JsonParseNodeResult @json_parse_value_node(ptr",
				"define %JsonParseNodeResult @json_parse_array_node(ptr",
				"define %JsonParseNodeResult @json_parse_object_node(ptr",
				"define i8 @json_ast_kind(i32 %0, %JsonNode__Store %1)",
				"define %JsonAstArrayIterCursor @json_ast_array_iter_first(i32 %0, %JsonNode__Store %1)",
				"define %JsonAstObjectIterCursor @json_ast_object_iter_first(i32 %0, %JsonNode__Store %1)",
				"define i32 @json_ast_array_nth(i32 %0, i64 %1, %JsonNode__Store %2)",
				"define i32 @json_ast_object_get(i32 %0, ptr %1, ptr %2, %JsonNode__Store %3)",
				"define i64 @json_parser_parity_suite()",
				"define i64 @json_parser_checksum(ptr",
				"define i64 @json_parser_ast_checksum(ptr",
				"define i64 @json_parser_ast_object_len(ptr",
				"define i64 @json_parser_ast_field_string_eq(ptr",
				"define i64 @json_parser_ast_field_kind(ptr",
				"define i64 @json_parser_ast_object_field_len(ptr",
				"define i64 @json_parser_ast_field_number_kind(ptr",
				"define i64 @json_parser_ast_field_string_len(ptr",
				"define i64 @json_parser_ast_field_string_copy(ptr",
				"define i64 @json_parser_ast_field_i64(ptr",
				"define i64 @json_parser_ast_field_u64(ptr",
				"define i64 @json_parser_ast_field_f64(ptr",
				"define i64 @json_parser_ast_field_f32(ptr",
				"define i64 @json_parser_ast_array_field_i64_at(ptr",
				"define i64 @json_parser_ast_array_field_f64_at(ptr",
				"define i64 @json_parser_ast_array_field_f32_at(ptr",
				"define i64 @json_parser_ast_array_field_kind_at(ptr",
				"define i64 @json_parser_ast_array_field_number_kind_at(ptr",
				"define i64 @json_parser_ast_array_field_string_len_at(ptr",
				"define i64 @json_parser_ast_array_field_string_copy_at(ptr",
				"define i64 @json_parser_ast_array_field_string_eq_at(ptr",
				"define i64 @json_parser_ast_array_field_bool_at(ptr",
				"define i64 @json_parser_ast_array_field_is_null_at(ptr",
				"define i64 @json_parser_ast_array_field_array_len_at(ptr",
				"define i64 @json_parser_ast_array_field_object_len_at(ptr",
				"define i64 @json_parser_ast_object_key_eq_at(ptr",
				"define i64 @json_parser_ast_object_key_len_at(ptr",
				"define i64 @json_parser_ast_object_key_copy_at(ptr",
				"define i64 @json_parser_ast_object_field_i64_at(ptr",
				"define i64 @json_parser_ast_object_field_f64_at(ptr",
				"define i64 @json_parser_ast_object_field_f32_at(ptr",
				"define i64 @json_parser_ast_object_value_string_eq_at(ptr",
				"define i64 @json_parser_ast_object_field_bool_at(ptr",
				"define i64 @json_parser_ast_object_field_is_null_at(ptr",
				"define i64 @json_parser_ast_object_value_kind_at(ptr",
				"define i64 @json_parser_ast_object_value_array_len_at(ptr",
				"define i64 @json_parser_ast_object_value_object_len_at(ptr",
				"define i64 @json_parser_ast_object_value_number_kind_at(ptr",
				"define i64 @json_parser_ast_object_value_string_len_at(ptr",
				"define i64 @json_parser_ast_object_value_string_copy_at(ptr",
				"define i64 @json_parser_ast_array_i64_at(ptr",
				"define i64 @json_parser_ast_array_f64_at(ptr",
				"define i64 @json_parser_ast_array_f32_at(ptr",
				"define i64 @json_parser_ast_array_kind_at(ptr",
				"define i64 @json_parser_ast_array_array_len_at(ptr",
				"define i64 @json_parser_ast_array_object_len_at(ptr",
				"define i64 @json_parser_ast_array_number_kind_at(ptr",
				"define i64 @json_parser_ast_array_string_len_at(ptr",
				"define i64 @json_parser_ast_array_string_copy_at(ptr",
				"define i64 @json_parser_ast_array_string_eq_at(ptr",
				"define i64 @json_parser_ast_array_bool_at(ptr",
				"define i64 @json_parser_ast_array_is_null_at(ptr",
				"%JsonParserDocument = type { i64 }",
				"define i64 @json_parser_document_parse(ptr",
				"define i64 @json_parser_document_destroy(i64",
				"define i64 @json_parser_document_checksum(ptr",
				"define i64 @json_parser_document_node_count(ptr",
				"define i64 @json_parser_document_root_kind(ptr",
				"define i64 @json_parser_document_object_len(ptr",
				"define i64 @json_parser_document_array_len(ptr",
				"define i64 @json_parser_document_field_kind(ptr",
				"define i64 @json_parser_document_field_string_copy(ptr",
				"define i64 @json_parser_document_field_i64(ptr",
				"define i64 @json_parser_document_field_f64(ptr",
				"define i64 @json_parser_document_field_f32(ptr",
				"define i64 @json_parser_document_array_field_i64_at(ptr",
				"define i64 @json_parser_document_array_field_f64_at(ptr",
				"define i64 @json_parser_document_array_field_f32_at(ptr",
				"define i64 @json_parser_document_object_key_copy_at(ptr",
				"define i64 @json_parser_document_object_value_string_copy_at(ptr",
				"define i64 @json_parser_document_object_field_f64_at(ptr",
				"define i64 @json_parser_document_object_field_f32_at(ptr",
				"define i64 @json_parser_document_array_string_copy_at(ptr",
				"define i64 @json_parser_document_array_f64_at(ptr",
				"define i64 @json_parser_document_array_f32_at(ptr",
				"%JsonParserValue = type { i64, ptr }",
				"define i64 @json_parser_document_root_value(ptr",
				"define i64 @json_parser_value_is_valid(ptr",
				"define i64 @json_parser_value_kind(ptr",
				"define i64 @json_parser_value_object_len(ptr",
				"define i64 @json_parser_value_array_len(ptr",
				"define i64 @json_parser_value_field(ptr",
				"define i64 @json_parser_value_index(ptr",
				"define i64 @json_parser_value_object_key_at(ptr",
				"define i64 @json_parser_value_object_value_at(ptr",
				"define i64 @json_parser_value_string_eq(ptr",
				"define i64 @json_parser_value_field_kind(ptr",
				"define i64 @json_parser_value_field_string_eq(ptr",
				"define i64 @json_parser_value_field_i64(ptr",
				"define i64 @json_parser_value_field_f64(ptr",
				"define i64 @json_parser_value_field_array_len(ptr",
				"define i64 @json_parser_value_index_kind(ptr",
				"define i64 @json_parser_value_index_string_eq(ptr",
				"define i64 @json_parser_value_index_i64(ptr",
				"define i64 @json_parser_value_index_f64(ptr",
				"define i64 @json_parser_value_index_array_len(ptr",
				"define i64 @json_parser_value_index_object_len(ptr",
				"define i64 @json_parser_value_string_copy(ptr",
				"define i64 @json_parser_value_i64(ptr",
				"define i64 @json_parser_value_u64(ptr",
				"define i64 @json_parser_value_f64(ptr",
				"define i64 @json_parser_value_f32(ptr",
				"%JsonParserArrayIter = type { i64, ptr, i64, i64 }",
				"%JsonParserObjectIter = type { i64, ptr, i64, i64 }",
				"define i64 @json_parser_value_array_iter(ptr",
				"define i64 @json_parser_value_object_iter(ptr",
				"define i64 @json_parser_array_iter_is_valid(ptr",
				"define i64 @json_parser_array_iter_kind(ptr",
				"define i64 @json_parser_array_iter_string_eq(ptr",
				"define i64 @json_parser_array_iter_i64(ptr",
				"define i64 @json_parser_array_iter_f64(ptr",
				"define i64 @json_parser_array_iter_array_len(ptr",
				"define i64 @json_parser_array_iter_object_len(ptr",
				"define i64 @json_parser_array_iter_value(ptr",
				"define i64 @json_parser_array_iter_next(ptr",
				"define i64 @json_parser_object_iter_is_valid(ptr",
				"define i64 @json_parser_object_iter_key_eq(ptr",
				"define i64 @json_parser_object_iter_field_kind(ptr",
				"define i64 @json_parser_object_iter_field_string_eq(ptr",
				"define i64 @json_parser_object_iter_field_f64(ptr",
				"define i64 @json_parser_object_iter_field_array_len(ptr",
				"define i64 @json_parser_object_iter_key_string_eq(ptr",
				"define i64 @json_parser_object_iter_value_kind(ptr",
				"define i64 @json_parser_object_iter_value_string_eq(ptr",
				"define i64 @json_parser_object_iter_value_f64(ptr",
				"define i64 @json_parser_object_iter_value_array_len(ptr",
				"define i64 @json_parser_object_iter_value_object_len(ptr",
				"define i64 @json_parser_object_iter_key(ptr",
				"define i64 @json_parser_object_iter_value(ptr",
				"define i64 @json_parser_object_iter_next(ptr",
				"define i64 @json_parallel_worker(%JsonParallelJob",
				"define i64 @json_parser_parallel_max_workers()",
				"define i64 @json_parser_parallel_checksum(",
				"define i64 @json_parser_parallel_ast_checksum(",
				"call %ThreadPool @pool_new(",
				"call void @task_group_wait_all_raw(ptr",
			},
		},
		{
			name: "grammar_surface_precedence",
			path: filepath.Join(repoRoot, "Code", "test_programs", "grammar_surface_precedence.elisa"),
			checks: []string{
				"%Token = type { i32 }",
				"define %Token @grammar_surface_parse_expr(ptr",
				"define %Token @grammar_surface_parse_one_off(ptr",
				"@__grammar_try__Arithmetic____grammar_precedence_Arithmetic_expression_1_compare(",
				"@__grammar_try__Arithmetic____grammar_precedence_Arithmetic_one_off_expression_1_inline(",
			},
		},
		{
			name: "fact_core_rules",
			path: filepath.Join(repoRoot, "Code", "test_programs", "fact_core_rules.elisa"),
			checks: []string{
				"%FactPlayer__Alive = type { i64 }",
				"define i64 @fact_core_rules(",
				"define i32 @fact_core_error_path(",
			},
		},
		{
			name: "fact_interface_rules",
			path: filepath.Join(repoRoot, "Code", "test_programs", "fact_interface_rules.elisa"),
			checks: []string{
				"define i64 @__impl__FactBuilder__semantic.StructType_FactBuilderTag__state()",
				"define i64 @fact_interface_rules__FactBuilderTag(",
				"define i64 @fact_interface_concrete(",
			},
		},
		{
			name: "grammar_uses_shared_helpers",
			path: filepath.Join(repoRoot, "Code", "test_programs", "grammar_uses_shared_helpers.elisa"),
			checks: []string{
				"%Token = type { i32 }",
				"define %Token @grammar_uses_parse_statement(ptr",
				"define %Token @grammar_uses_recovering_atom(ptr",
				"@__grammar_try__StatementGrammar____grammar_precedence_StatementGrammar_statement_1_compare(",
				"call void @record_parse_error(ptr",
				"@__grammar_try__StatementGrammar__recovering_atom(",
			},
		},
		{
			name: "string_escapes",
			path: filepath.Join(repoRoot, "Code", "test_programs", "string_escapes.elisa"),
			checks: []string{
				"define ptr @newline_text()",
				"define ptr @quoted_text()",
				"define ptr @unicode_text()",
			},
		},
		{
			name: "char_literals",
			path: filepath.Join(repoRoot, "Code", "test_programs", "char_literals.elisa"),
			checks: []string{
				"define i64 @char_code()",
				"define i64 @escaped_char_code()",
				"define i1 @char_compare()",
				"define i64 @char_array_checksum()",
			},
		},
		{
			name: "value_optionals",
			path: filepath.Join(repoRoot, "Code", "test_programs", "value_optionals.elisa"),
			checks: []string{
				"%Box = type { i64 }",
				"%Optional__int = type { i1, i64 }",
				"%Optional__Box = type { i1, %Box }",
				"define %Optional__int @maybe_value(i1",
				"define i64 @fallback_value(i1",
				"extractvalue %Optional__int",
				"define %Optional__Box @maybe_box(i1",
				"define i64 @unwrap_or(i1",
				"getelementptr inbounds nuw %Optional__Box",
				"getelementptr inbounds nuw %Box",
			},
		},
		{
			name: "concurrency_explicit",
			path: filepath.Join(repoRoot, "Code", "test_programs", "concurrency_explicit.elisa"),
			checks: []string{
				"%Thread__i64__Joinable = type { i64, ptr }",
				"%Task__i64__Pending = type { i64, ptr }",
				"%ThreadPool = type { ptr }",
				"%TaskGroup = type { ptr, ptr }",
				"%Mutex = type { ptr }",
				"%MutexGuard__Held = type { ptr }",
				"%CondVar = type { ptr }",
				"%atomic__i64 = type { i64 }",
				"%ConcurrencyWorkStart1 = type { i64, ptr, ptr, %atomic__i64 }",
				"%ConcurrencyTaskGroupNode = type { ptr, ptr }",
				"%ConcurrencyBox__i64 = type { i64 }",
				"define i64 @atomic_roundtrip()",
				"define i1 @concurrency_handles(",
				"define %Thread__i64__Joinable @typed_thread_spawn(i64",
				"define %Thread__i64__Joinable @typed_thread_spawn_permissioned(i64",
				"define i64 @typed_thread_join(%Thread__i64__Joinable",
				"define void @typed_thread_detach_permissioned(i64",
				"define i64 @typed_pool_roundtrip(ptr",
				"define void @typed_group_waitall(ptr",
				"define i64 @typed_pool_scope(i64",
				"define i64 @runtime_carrier_worker(%SharedGate",
				"define i64 @typed_runtime_carrier_transfer(ptr",
				"define void @typed_notify_scope(%CondVar",
				"define i64 @permissioned_thread_worker(i64",
				"define %Thread__i64__Joinable @spawn1__i64__i64(",
				"define i64 @join__i64(",
				"define void @detach__i64(",
				"define %Task__i64__Pending @pool_submit1__i64__i64(",
				"define i64 @pool_await__i64(",
				"declare void @notify_one(ptr)",
				"declare void @notify_all(ptr)",
				"call void @pool_shutdown(ptr",
				"define %TaskGroup @task_group_new()",
				"define void @task_group_add__i64(",
				"define void @task_group_wait_all(ptr",
				"define ptr @ctx_concurrency_work1_entry__i64__i64(",
				"define i64 @ctx_concurrency_work1_take_result__i64(",
				"call void @store__i64(",
				"call i1 @compare_exchange__i64(",
				"call i64 @exchange__i64(",
				"call i64 @fetch_add(",
				"call i64 @fetch_sub(",
				"call i64 @fetch_or(",
				"call i64 @fetch_and(",
				"call i64 @fetch_xor(",
				"call i64 @load__i64(",
				"call void @fence(i32",
			},
		},
	}

	for _, fixture := range fixtures {
		fixture := fixture
		t.Run(fixture.name, func(t *testing.T) {
			var stdout bytes.Buffer
			var stderr bytes.Buffer
			exitCode := runCLI([]string{"-emit", "llvm", fixture.path}, &stdout, &stderr)
			if exitCode != 0 {
				t.Fatalf("runCLI returned %d\nstderr:\n%s", exitCode, stderr.String())
			}
			if stderr.Len() != 0 {
				t.Fatalf("expected no stderr output, got:\n%s", stderr.String())
			}
			output := stdout.String()
			for _, check := range fixture.checks {
				if !strings.Contains(output, check) {
					t.Fatalf("expected output to contain %q, got:\n%s", check, output)
				}
			}
		})
	}
}
