package semantic

import (
	"elisacore/src/ast"
)

// markTypestateStateFieldsForErasure identifies struct fields that carry typestate state markers
// and marks them for exclusion from runtime layout. A typestate-bearing struct generated by the
// parser has a generic parameter with Kind==GenericParamState and a corresponding `__typestate`
// field that tracks the state at runtime. This function:
//
// 1. Detects when a struct has a GenericParamState parameter (the typestate marker).
// 2. Marks the `__typestate` field as phantom (compile-time only, zero runtime bytes).
//
// The `__typestate` field remains visible to the semantic layer (for state checking and
// construction), but the backend's codegen layer will skip it when building struct layout
// (using the Phantom flag). This implements docs/111 S0: recognition and erasure of typestate
// state tokens as phantom type parameters from the LLVM layout perspective.
//
// NOTE: typestate transitions are not yet enforced — that arrives in S1 with transition
// functions and state-poststate discharge.
func (a *Analyzer) markTypestateStateFieldsForErasure(stDecl *ast.StructDecl, st *StructType) {
	if stDecl == nil || st == nil {
		return
	}

	// Check if this struct has a generic parameter with Kind==GenericParamState (the typestate marker).
	hasStateParam := false
	for _, gp := range stDecl.GenericParams {
		if gp.Kind == ast.GenericParamState {
			hasStateParam = true
			break
		}
	}

	if !hasStateParam {
		return
	}

	// This struct is typestate-bearing. Mark the __typestate field as phantom so the backend
	// skips it during LLVM struct layout generation.
	st.HasTypestate = true
	for _, field := range stDecl.Fields {
		if field.Name == "__typestate" {
			// Mark the field as phantom (erased from layout) in the semantic type.
			// The field remains in st.Fields and Decl.Fields so state checking and
			// construction still work, but codegen will skip it.
			if semField, ok := st.Fields["__typestate"]; ok {
				semField.Phantom = true
				st.Fields["__typestate"] = semField
			}
			st.TypestateStateField = "__typestate"
			break
		}
	}
}

// hasTypestateMarker returns true if a struct type has been marked as carrying typestate state.
func (st *StructType) hasTypestateMarker() bool {
	return st != nil && st.HasTypestate
}
