//go:build cgo

// Package semantic — metamorphic soundness test for the static verifier.
//
// PROPERTY (metamorphic oracle):
//   For every generated Elisa function whose `ensure` postcondition is FALSE
//   for at least one concrete input in our sample, the prover must REJECT it
//   under -strict (EnforceStrictProofs=true, EnableSMT=true). If the prover
//   ACCEPTS such a function, that is a false-acceptance unsoundness.
//
// GENERATION STRATEGY:
//   • Two param types: i64 (signed two's-complement wrap) and u64 (unsigned mod 2^64).
//   • Body computes one of: a+b, a-b, a*b, a/b (b≠0 guarded), a%b (b≠0 guarded),
//     a (identity), -a (negate, i64 only).
//   • Claim compares result to a linear/constant expression via ==, !=, <, <=, >, >=.
//   • Claims are generated by:
//       (A) KNOWN-FALSE: deliberately wrong constant offset or wrong operator.
//       (B) BOUNDARY: off-by-one at 0, ±1, max/min values.
//       (C) RANDOM-SWEEP: pseudo-random (lcg from fixed seed) param/op/const choices,
//           ground-truth evaluated in Go; if false for any sampled input → expect reject.
//   • Sampling: 16 concrete inputs per function (covering 0, ±1, large magnitudes).
//   • Total generated cases: ~300 (bounded for CI speed; each case is a single parse+analyze).
//
// WRAP SEMANTICS in Go ground-truth:
//   • i64 arithmetic uses int64 which wraps on overflow identically to two's-complement.
//   • u64 uses uint64 (Go's natural unsigned arithmetic, wraps mod 2^64).
//
// UNSOUNDNESS DETECTION:
//   A case is flagged as unsound when:
//     proverAccepted(src) == true  &&  groundTruthFalse(body, claim, inputs) == true
//   The test fails with a minimal reproducer (the Elisa source snippet).

package semantic

import (
	"fmt"
	"math"
	"strings"
	"testing"
)

// ── tiny LCG PRNG (fixed seed, fully deterministic) ──────────────────────────

type lcg struct{ state uint64 }

func newLCG(seed uint64) *lcg { return &lcg{seed} }

// next returns a pseudo-random uint64.
func (g *lcg) next() uint64 {
	// Knuth's multiplicative LCG (mod 2^64).
	g.state = g.state*6364136223846793005 + 1442695040888963407
	return g.state
}

func (g *lcg) nextI64() int64  { return int64(g.next()) }
func (g *lcg) nextU64() uint64 { return g.next() }

// nextIntn returns a non-negative int in [0,n).
func (g *lcg) nextIntn(n int) int { return int(g.next()>>1) % n }

// ── ground-truth concrete inputs ──────────────────────────────────────────────

// canonical sample values for i64 (cover 0, ±1, near-overflow, mid range).
var i64Samples = []int64{
	0, 1, -1, 2, -2, 100, -100,
	math.MaxInt64, math.MinInt64,
	math.MaxInt64 - 1, math.MinInt64 + 1,
	127, -128, 256, -256, 1024,
}

// canonical sample values for u64.
var u64Samples = []uint64{
	0, 1, 2, 100, 255, 256, 1024,
	math.MaxUint64, math.MaxUint64 - 1,
	math.MaxUint64 / 2, math.MaxUint64/2 + 1,
	1<<32 - 1, 1 << 32,
}

// ── case representation ───────────────────────────────────────────────────────

type numKind int

const (
	kindI64 numKind = iota
	kindU64
)

type bodyOp int

const (
	opAdd bodyOp = iota // a + b
	opSub               // a - b
	opMul               // a * b
	opDiv               // a / b  (b != 0)
	opMod               // a % b  (b != 0)
	opIdentA            // a
	opNegA              // -a  (i64 only; u64 wrapping negation, ~a+1)
)

type relOp int

const (
	relEQ relOp = iota // ==
	relNE               // !=
	relLT               // <
	relLE               // <=
	relGT               // >
	relGE               // >=
)

func (r relOp) String() string {
	return [...]string{"==", "!=", "<", "<=", ">", ">="}[r]
}

type metaCase struct {
	kind       numKind
	op         bodyOp
	rel        relOp
	claimConst int64 // RHS of claim: result <rel> claimConst
}

// ── Elisa source synthesis ────────────────────────────────────────────────────

func typeName(k numKind) string {
	if k == kindI64 {
		return "i64"
	}
	return "u64"
}

// bodyExpr returns the Elisa expression for the body computation.
func bodyExpr(op bodyOp, k numKind) string {
	switch op {
	case opAdd:
		return "a + b"
	case opSub:
		return "a - b"
	case opMul:
		return "a * b"
	case opDiv:
		return "a / b"
	case opMod:
		return "a % b"
	case opIdentA:
		return "a"
	case opNegA:
		if k == kindI64 {
			return "0 - a"
		}
		return "0 - a" // u64 wrapping negation
	}
	panic("unknown op")
}

// needsNonZeroB returns true when the body divides/mods by b.
func needsNonZeroB(op bodyOp) bool { return op == opDiv || op == opMod }

// hasBParam returns true when the body uses a second parameter b.
func hasBParam(op bodyOp) bool {
	switch op {
	case opAdd, opSub, opMul, opDiv, opMod:
		return true
	}
	return false
}

// synthElisaSrc generates an Elisa source snippet for a metaCase.
func synthElisaSrc(c metaCase, id int) string {
	t := typeName(c.kind)
	body := bodyExpr(c.op, c.kind)

	// ensure rhs literal — Elisa needs type-appropriate literal
	var rhsLit string
	if c.kind == kindI64 {
		rhsLit = fmt.Sprintf("%d", c.claimConst)
	} else {
		// u64: claimConst may be negative from our generator; use wrapping uint64
		rhsLit = fmt.Sprintf("%d", uint64(c.claimConst))
	}

	var params string
	if hasBParam(c.op) {
		params = fmt.Sprintf("a: %s, b: %s", t, t)
	} else {
		params = fmt.Sprintf("a: %s", t)
	}

	var requires string
	if needsNonZeroB(c.op) {
		requires = fmt.Sprintf("\n    requires b != 0")
	}

	return fmt.Sprintf(`def f%d(%s) -> %s:%s
    ensure result %s %s
    return %s
`, id, params, t, requires, c.rel.String(), rhsLit, body)
}

// ── Go ground-truth evaluator ─────────────────────────────────────────────────

// evalBodyI64 evaluates the body for i64 (wraps on overflow — Go int64 does this natively).
func evalBodyI64(op bodyOp, a, b int64) int64 {
	switch op {
	case opAdd:
		return a + b
	case opSub:
		return a - b
	case opMul:
		return a * b
	case opDiv:
		if b == 0 {
			return 0
		}
		return a / b
	case opMod:
		if b == 0 {
			return 0
		}
		return a % b
	case opIdentA:
		return a
	case opNegA:
		return -a
	}
	panic("unknown op")
}

func evalBodyU64(op bodyOp, a, b uint64) uint64 {
	switch op {
	case opAdd:
		return a + b
	case opSub:
		return a - b
	case opMul:
		return a * b
	case opDiv:
		if b == 0 {
			return 0
		}
		return a / b
	case opMod:
		if b == 0 {
			return 0
		}
		return a % b
	case opIdentA:
		return a
	case opNegA:
		return 0 - a // wrapping negation
	}
	panic("unknown op")
}

func evalRelI64(result, rhs int64, rel relOp) bool {
	switch rel {
	case relEQ:
		return result == rhs
	case relNE:
		return result != rhs
	case relLT:
		return result < rhs
	case relLE:
		return result <= rhs
	case relGT:
		return result > rhs
	case relGE:
		return result >= rhs
	}
	panic("unknown rel")
}

func evalRelU64(result, rhs uint64, rel relOp) bool {
	switch rel {
	case relEQ:
		return result == rhs
	case relNE:
		return result != rhs
	case relLT:
		return result < rhs
	case relLE:
		return result <= rhs
	case relGT:
		return result > rhs
	case relGE:
		return result >= rhs
	}
	panic("unknown rel")
}

// claimIsFalseForSomeInput returns (false, "") when the claim holds on all
// sampled inputs, or (true, witness) when a counterexample is found.
func claimIsFalseForSomeInput(c metaCase) (bad bool, witness string) {
	rhsI64 := c.claimConst
	rhsU64 := uint64(c.claimConst)

	check := func(a, b int64) bool {
		if needsNonZeroB(c.op) && b == 0 {
			return true // skip — requires b != 0 guards this
		}
		if c.kind == kindI64 {
			result := evalBodyI64(c.op, a, b)
			return evalRelI64(result, rhsI64, c.rel)
		}
		ua, ub := uint64(a), uint64(b)
		result := evalBodyU64(c.op, ua, ub)
		return evalRelU64(result, rhsU64, c.rel)
	}

	if !hasBParam(c.op) {
		for _, a := range i64Samples {
			if !check(a, 0) {
				return true, fmt.Sprintf("a=%d", a)
			}
		}
		return false, ""
	}

	for _, a := range i64Samples {
		for _, b := range i64Samples {
			if !check(a, b) {
				return true, fmt.Sprintf("a=%d b=%d", a, b)
			}
		}
	}
	return false, ""
}

// ── prover acceptance check ───────────────────────────────────────────────────

// proverAccepts returns true when the strict prover accepts the given source
// (i.e. issues no "could not be proven statically" diagnostics).
func proverAccepts(t *testing.T, name, src string) bool {
	t.Helper()
	result := analyzeFunctionAnalysisTestSourceWithOptionsAllowingDiagnostics(t, name, src,
		AnalyzeOptions{EnableSMT: true, EnforceStrictProofs: true})
	allErrs := strings.Join(result.Errors(), "\n")
	return !strings.Contains(allErrs, "could not be proven statically")
}

// ── case generation ───────────────────────────────────────────────────────────

// allBodyOps enumerates ops per kind.
func opsForKind(k numKind) []bodyOp {
	ops := []bodyOp{opAdd, opSub, opMul, opDiv, opMod, opIdentA, opNegA}
	if k == kindU64 {
		// negation also works for u64 (wrapping), so include all
		return ops
	}
	return ops
}

var allRelOps = []relOp{relEQ, relNE, relLT, relLE, relGT, relGE}
var allKinds = []numKind{kindI64, kindU64}

// generateDeterministicCases produces the full case set using a fixed seed.
// Strategy:
//  1. KNOWN-FALSE sweep: for each (kind, op), claim "result == <constant that is
//     wrong for all inputs>" — e.g. for a+b, claim result == MaxInt64+1 (wraps to MinInt64).
//     These are almost certainly false for some input.
//  2. BOUNDARY sweep: for each (kind, op, rel), claim against 0, 1, -1 (boundary constants).
//  3. RANDOM sweep: pseudo-random combinations seeded deterministically.
func generateDeterministicCases() []metaCase {
	cases := make([]metaCase, 0, 400)
	g := newLCG(0xdeadbeef_cafebabe)

	// ── (1) KNOWN-FALSE: deliberately wrong constant ──────────────────────────
	// For every (kind, op) pair, pick a constant C such that the claim
	// "result == C" is virtually guaranteed false for at least one sample.
	// We use C = 999999937 (a large prime) which won't match arithmetic over 0-inputs.
	knownFalseConsts := []int64{999999937, -999999937, 42, -42, 1234567890, -1234567890}
	for _, k := range allKinds {
		for _, op := range opsForKind(k) {
			for _, cst := range knownFalseConsts {
				cases = append(cases, metaCase{kind: k, op: op, rel: relEQ, claimConst: cst})
			}
		}
	}

	// ── (2) BOUNDARY sweep: all rel-ops against {-1, 0, 1} ───────────────────
	boundaryCsts := []int64{-1, 0, 1, 2, -2, math.MaxInt64, math.MinInt64}
	for _, k := range allKinds {
		for _, op := range opsForKind(k) {
			for _, rel := range allRelOps {
				for _, cst := range boundaryCsts {
					cases = append(cases, metaCase{kind: k, op: op, rel: rel, claimConst: cst})
				}
			}
		}
	}

	// ── (3) RANDOM sweep ─────────────────────────────────────────────────────
	ops := opsForKind(kindI64) // same length for both kinds
	for i := 0; i < 200; i++ {
		k := allKinds[g.nextIntn(len(allKinds))]
		op := ops[g.nextIntn(len(ops))]
		rel := allRelOps[g.nextIntn(len(allRelOps))]
		cst := g.nextI64() // arbitrary random constant
		cases = append(cases, metaCase{kind: k, op: op, rel: rel, claimConst: cst})
	}

	return cases
}

// ── THE TEST ──────────────────────────────────────────────────────────────────

// TestProverMetamorphicSoundness is the main soundness property test.
// It generates a deterministic batch of Elisa programs with `ensure` postconditions
// and checks that the prover NEVER accepts a claim that is false for some concrete input.
func TestProverMetamorphicSoundness(t *testing.T) {
	cases := generateDeterministicCases()

	type finding struct {
		id      int
		src     string
		witness string
	}
	var unsound []finding

	accepted := 0
	rejected := 0
	skipped := 0
	trueForAll := 0

	for i, c := range cases {
		src := synthElisaSrc(c, i)

		// Ground truth: is the claim false for at least one sampled input?
		isFalse, witness := claimIsFalseForSomeInput(c)
		if !isFalse {
			// Claim appears true on all our samples. We don't test this case
			// for false-acceptance (we don't know ground truth with certainty).
			trueForAll++
			continue
		}

		// The claim IS false for some input. The prover must reject this.
		// If it accepts, we have an unsoundness.
		name := fmt.Sprintf("metamorphic_case_%d.elisa", i)

		// Quick parse check: skip if the source doesn't parse/analyze without
		// *contract* errors (it may fail for other reasons like type errors on
		// boundary i64/u64 literal overflow in claims — that's ok, not unsound).
		result := analyzeFunctionAnalysisTestSourceWithOptionsAllowingDiagnostics(t, name, src,
			AnalyzeOptions{EnableSMT: true, EnforceStrictProofs: true})
		allErrs := strings.Join(result.Errors(), "\n")

		// If analysis itself failed for non-contract reasons, skip the case.
		// We detect contract-proof errors by the well-known diagnostic string.
		// Any other error (type error, parse issue embedded in analyze) means the
		// source was invalid for reasons unrelated to contract soundness.
		hasContractDiag := strings.Contains(allErrs, "could not be proven statically")
		hasOtherErr := len(result.Errors()) > 0 && !hasContractDiag &&
			!strings.Contains(allErrs, "prove")
		// A more liberal skip: if there are errors that are NOT contract-proof errors,
		// the case is invalid (e.g., literal out of range), so skip.
		if len(result.Errors()) > 0 && !hasContractDiag {
			skipped++
			continue
		}

		_ = hasOtherErr

		if hasContractDiag {
			// Prover correctly rejected the false claim.
			rejected++
		} else {
			// Prover accepted — but the claim is false for input: witness.
			accepted++
			unsound = append(unsound, finding{id: i, src: src, witness: witness})
		}
	}

	// Report summary.
	t.Logf("Metamorphic soundness: total=%d true-for-all-samples=%d false-for-some-input=%d (rejected=%d accepted=%d skipped=%d)",
		len(cases), trueForAll, rejected+accepted+skipped, rejected, accepted, skipped)

	if len(unsound) > 0 {
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("SOUNDNESS VIOLATIONS: %d case(s) where the prover accepted a provably-false ensure clause.\n\n", len(unsound)))
		for _, f := range unsound {
			sb.WriteString(fmt.Sprintf("=== Case %d (witness: %s) ===\n%s\n", f.id, f.witness, f.src))
		}
		t.Fatal(sb.String())
	}
}

// TestProverMetamorphicKnownTrue verifies the test harness isn't broken by
// confirming a selection of provably-TRUE postconditions are accepted.
func TestProverMetamorphicKnownTrue(t *testing.T) {
	truePrograms := []struct {
		name string
		src  string
	}{
		{
			name: "identity_eq",
			src: `def f(a: i64) -> i64:
    ensure result == a
    return a
`,
		},
		{
			name: "add_ge_a",
			src: `def f(a: i64) -> i64:
    requires a >= 0
    ensure result >= 0
    return a
`,
		},
		{
			name: "const_return",
			src: `def f(a: i64) -> i64:
    ensure result == 42
    return 42
`,
		},
		{
			name: "zero_identity",
			src: `def f() -> i64:
    ensure result == 0
    return 0
`,
		},
	}

	for _, tc := range truePrograms {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			if !proverAccepts(t, tc.name+".elisa", tc.src) {
				t.Fatalf("prover rejected a known-true ensure: %s\n%s", tc.name, tc.src)
			}
		})
	}
}
